# Generated by Django 5.2.12 on 2026-03-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
